### Numpy

In [1]:
import numpy as np

In [5]:
arr_1d = np.array([1,2,3,4,5])

print(arr_1d)

arr_2d = np.array([[1,2,3,4],[6,7,8,9]])

print(arr_2d)

[1 2 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]


### List vs numpy arrays


In [7]:
py_list = [1,2,3,4,5]
print(py_list * 2)

arr = np.array([1,2,3,4])
print(arr * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2 4 6 8]


### Creating arrays from scratch

In [11]:
zeros = np.zeros((4,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
full = np.full((1,2),7)
print(full)

[[7 7]]


In [16]:
random = np.random.random((2,3))
print(random)

[[0.83141468 0.28435343 0.40654255]
 [0.66451407 0.78822168 0.63530576]]


In [20]:
sequence = np.arange(0,10,2)
print(sequence)

[0 2 4 6 8]


### Vector , Matrix , Tensor

In [21]:
vector = np.array([1,2,3,4])
print(vector)

[1 2 3 4]


In [22]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [23]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array's properties

In [27]:
arr = np.array([[1,2,3],[4,5,6]])
print('shape:', arr.shape)
print('Size:', arr.size)
print('Dimension:', arr.ndim)
print('Dtype:', arr.dtype)

shape: (2, 3)
Size: 6
Dimension: 2
Dtype: int64


array Reshaping

In [ ]:
original = np.arange(12)
print(original)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [40]:
reshaped= original.reshape((3,4))
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
transpose = reshaped.T
print(transpose)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [43]:
flattened = reshaped.flatten()
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
raveled = reshaped.ravel()
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
