### Numpy Operation

In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print('basic slicing', arr[2:8])
print('with step', arr[1:8:2])
print('negative', arr[-2])

basic slicing [3 4 5 6 7 8]
with step [2 4 6 8]
negative 8


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('specific element', arr_2d[1,2])
print('row', arr_2d[1])
print('column', arr_2d[:,1])


specific element 6
row [4 5 6]
row [2 5 8]


### Sorted

In [18]:
unsorted = np.array([4,5,7,2,3,46,21])
print('sorted', np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print('2d sorted column', np.sort(arr_2d_unsorted, axis = 0))

sorted [ 2  3  4  5  7 21 46]
2d sorted column [[1 1]
 [2 2]
 [3 3]]


### Filtering

In [35]:
numbers = np.arange(1,11)
even = numbers[numbers % 2 == 0]
print(even)

[ 2  4  6  8 10]


### Filtering with Mask

In [ ]:
mask = even[even > 5]
print(mask)

[ 6  8 10]


### Fancy indexing vs np.where()

In [36]:
indices = [0,2,4]
print(numbers[indices])

where_result = numbers[np.where(numbers>5)]
print(where_result)

[1 3 5]
[ 6  7  8  9 10]


In [38]:
conditons_array = np.where(numbers>5, numbers*2, numbers)
print(conditons_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing Data


In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibilty

In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print('Compatibilty shape', a.shape == b.shape)
print(c.shape)

Compatibilty shape True
(3,)


In [48]:
oringinal = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((oringinal,new_row))
print(oringinal)
print(new_row)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((oringinal, new_col))

print(oringinal)
print(new_col)
print(with_new_col)


[[1 2]
 [3 4]]
[5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[7]
 [8]]
[[1 2 7]
 [3 4 8]]


In [49]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5 6]
